version: '3.9'

services:
  postgres:
    container_name: postgres-container
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'yan-flashcards'
    volumes:
      - ddh-postgres:/var/lib/postgresql/data
    networks:
      - postgres

  redis:
    container_name: redis-container
    image: redis:alpine
    ports:
      - "6379:6379"
#    environment:
#      REDIS_PASSWORD: 'password'
    networks:
      - redis

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge

volumes:
  ddh-postgres: