apiVersion: apps/v1
kind: Deployment
metadata:
  name: yan-web-deployment
  labels:
    app: yan-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yan-web
  template:
    metadata:
      labels:
        app: yan-web
    spec:
      containers:
        - name: yan-web
          image: yan-web:latest
          ports:
            - containerPort: 80
