apiVersion: v1
kind: Service
metadata:
  name: yan-web-service
  labels:
    app: yan-web
spec:
  selector:
    app: yan-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP