apiVersion: v1
kind: Service
metadata:
  name: yan-api-service
  labels:
    app: yan-api
spec:
  selector:
    app: yan-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP